# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Development\PyQt\projects\Fluent\eric\mainwindow.ui'
#
# Created: Tue Apr 21 22:59:51 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(753, 570)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 711, 501))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 100, 661, 151))
        self.groupBox_15.setAutoFillBackground(False)
        self.groupBox_15.setFlat(False)
        self.groupBox_15.setCheckable(False)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayoutWidget_13 = QtGui.QWidget(self.groupBox_15)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(20, 30, 621, 112))
        self.gridLayoutWidget_13.setObjectName(_fromUtf8("gridLayoutWidget_13"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.le_fluent_jou_file = QtGui.QLineEdit(self.gridLayoutWidget_13)
        self.le_fluent_jou_file.setObjectName(_fromUtf8("le_fluent_jou_file"))
        self.gridLayout_14.addWidget(self.le_fluent_jou_file, 0, 2, 1, 1)
        self.btn_open_fluent_cas = QtGui.QPushButton(self.gridLayoutWidget_13)
        self.btn_open_fluent_cas.setObjectName(_fromUtf8("btn_open_fluent_cas"))
        self.gridLayout_14.addWidget(self.btn_open_fluent_cas, 1, 3, 1, 1)
        self.btn_open_fluent_jou = QtGui.QPushButton(self.gridLayoutWidget_13)
        self.btn_open_fluent_jou.setObjectName(_fromUtf8("btn_open_fluent_jou"))
        self.gridLayout_14.addWidget(self.btn_open_fluent_jou, 0, 3, 1, 1)
        self.label_100 = QtGui.QLabel(self.gridLayoutWidget_13)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout_14.addWidget(self.label_100, 0, 0, 1, 1)
        self.label_101 = QtGui.QLabel(self.gridLayoutWidget_13)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_14.addWidget(self.label_101, 1, 0, 1, 1)
        self.le_fluent_udf_file = QtGui.QLineEdit(self.gridLayoutWidget_13)
        self.le_fluent_udf_file.setObjectName(_fromUtf8("le_fluent_udf_file"))
        self.gridLayout_14.addWidget(self.le_fluent_udf_file, 2, 2, 1, 1)
        self.le_fluent_cas_file = QtGui.QLineEdit(self.gridLayoutWidget_13)
        self.le_fluent_cas_file.setObjectName(_fromUtf8("le_fluent_cas_file"))
        self.gridLayout_14.addWidget(self.le_fluent_cas_file, 1, 2, 1, 1)
        self.btn_load_jou_param = QtGui.QPushButton(self.gridLayoutWidget_13)
        self.btn_load_jou_param.setObjectName(_fromUtf8("btn_load_jou_param"))
        self.gridLayout_14.addWidget(self.btn_load_jou_param, 0, 4, 1, 1)
        self.btn_open_fluent_udf = QtGui.QPushButton(self.gridLayoutWidget_13)
        self.btn_open_fluent_udf.setObjectName(_fromUtf8("btn_open_fluent_udf"))
        self.gridLayout_14.addWidget(self.btn_open_fluent_udf, 2, 3, 1, 1)
        self.label_102 = QtGui.QLabel(self.gridLayoutWidget_13)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_14.addWidget(self.label_102, 2, 0, 1, 1)
        self.label_103 = QtGui.QLabel(self.gridLayoutWidget_13)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout_14.addWidget(self.label_103, 3, 0, 1, 1)
        self.le_fluent_load_file = QtGui.QLineEdit(self.gridLayoutWidget_13)
        self.le_fluent_load_file.setObjectName(_fromUtf8("le_fluent_load_file"))
        self.gridLayout_14.addWidget(self.le_fluent_load_file, 3, 2, 1, 1)
        self.btn_open_fluent_load = QtGui.QPushButton(self.gridLayoutWidget_13)
        self.btn_open_fluent_load.setObjectName(_fromUtf8("btn_open_fluent_load"))
        self.gridLayout_14.addWidget(self.btn_open_fluent_load, 3, 3, 1, 1)
        self.btn_load_udf_param = QtGui.QPushButton(self.gridLayoutWidget_13)
        self.btn_load_udf_param.setObjectName(_fromUtf8("btn_load_udf_param"))
        self.gridLayout_14.addWidget(self.btn_load_udf_param, 2, 4, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.tab)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 10, 661, 71))
        self.groupBox_14.setAutoFillBackground(False)
        self.groupBox_14.setFlat(False)
        self.groupBox_14.setCheckable(False)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.groupBox_14)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 20, 621, 31))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.le_proj_file = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.le_proj_file.setObjectName(_fromUtf8("le_proj_file"))
        self.gridLayout_8.addWidget(self.le_proj_file, 0, 2, 1, 1)
        self.btn_open_proj = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.btn_open_proj.setObjectName(_fromUtf8("btn_open_proj"))
        self.gridLayout_8.addWidget(self.btn_open_proj, 0, 3, 1, 1)
        self.label_91 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_8.addWidget(self.label_91, 0, 0, 1, 1)
        self.btn_new_proj = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.btn_new_proj.setObjectName(_fromUtf8("btn_new_proj"))
        self.gridLayout_8.addWidget(self.btn_new_proj, 0, 4, 1, 1)
        self.groupBox_19 = QtGui.QGroupBox(self.tab)
        self.groupBox_19.setGeometry(QtCore.QRect(20, 270, 661, 71))
        self.groupBox_19.setAutoFillBackground(False)
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayoutWidget_14 = QtGui.QWidget(self.groupBox_19)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(20, 20, 621, 31))
        self.gridLayoutWidget_14.setObjectName(_fromUtf8("gridLayoutWidget_14"))
        self.gridLayout_15 = QtGui.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.le_fluent_path = QtGui.QLineEdit(self.gridLayoutWidget_14)
        self.le_fluent_path.setObjectName(_fromUtf8("le_fluent_path"))
        self.gridLayout_15.addWidget(self.le_fluent_path, 0, 2, 1, 1)
        self.btn_open_fluent_path = QtGui.QPushButton(self.gridLayoutWidget_14)
        self.btn_open_fluent_path.setObjectName(_fromUtf8("btn_open_fluent_path"))
        self.gridLayout_15.addWidget(self.btn_open_fluent_path, 0, 3, 1, 1)
        self.label_104 = QtGui.QLabel(self.gridLayoutWidget_14)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout_15.addWidget(self.label_104, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 410, 661, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_save_proj = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_save_proj.setObjectName(_fromUtf8("btn_save_proj"))
        self.horizontalLayout_2.addWidget(self.btn_save_proj)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_20 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_20.setGeometry(QtCore.QRect(20, 10, 661, 301))
        self.groupBox_20.setAutoFillBackground(False)
        self.groupBox_20.setFlat(False)
        self.groupBox_20.setCheckable(False)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.groupBox_21 = QtGui.QGroupBox(self.groupBox_20)
        self.groupBox_21.setGeometry(QtCore.QRect(20, 20, 621, 121))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.gridLayoutWidget_10 = QtGui.QWidget(self.groupBox_21)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(20, 20, 581, 86))
        self.gridLayoutWidget_10.setObjectName(_fromUtf8("gridLayoutWidget_10"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.le_formula_copc_e = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_e.setObjectName(_fromUtf8("le_formula_copc_e"))
        self.gridLayout_11.addWidget(self.le_formula_copc_e, 3, 10, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 3, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 3, 8, 1, 1)
        self.le_formula_copc_a = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_a.setObjectName(_fromUtf8("le_formula_copc_a"))
        self.gridLayout_11.addWidget(self.le_formula_copc_a, 2, 10, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 2, 5, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 2, 8, 1, 1)
        self.label_59 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_11.addWidget(self.label_59, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_11.addWidget(self.label_25, 3, 0, 1, 1)
        self.le_formula_copc_b = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_b.setObjectName(_fromUtf8("le_formula_copc_b"))
        self.gridLayout_11.addWidget(self.le_formula_copc_b, 3, 1, 1, 1)
        self.le_formula_copc_f = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_f.setObjectName(_fromUtf8("le_formula_copc_f"))
        self.gridLayout_11.addWidget(self.le_formula_copc_f, 2, 1, 1, 1)
        self.le_formula_copc_m = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_m.setObjectName(_fromUtf8("le_formula_copc_m"))
        self.gridLayout_11.addWidget(self.le_formula_copc_m, 2, 4, 1, 1)
        self.label_71 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_11.addWidget(self.label_71, 2, 0, 1, 1)
        self.label_68 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_11.addWidget(self.label_68, 2, 6, 1, 1)
        self.label_73 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_11.addWidget(self.label_73, 2, 9, 1, 1)
        self.le_formula_copc_n = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_n.setObjectName(_fromUtf8("le_formula_copc_n"))
        self.gridLayout_11.addWidget(self.le_formula_copc_n, 2, 7, 1, 1)
        self.label_74 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_11.addWidget(self.label_74, 2, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_11.addWidget(self.label_26, 3, 3, 1, 1)
        self.le_formula_copc_c = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_c.setObjectName(_fromUtf8("le_formula_copc_c"))
        self.gridLayout_11.addWidget(self.le_formula_copc_c, 3, 4, 1, 1)
        self.label_60 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_11.addWidget(self.label_60, 3, 6, 1, 1)
        self.le_formula_copc_d = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.le_formula_copc_d.setObjectName(_fromUtf8("le_formula_copc_d"))
        self.gridLayout_11.addWidget(self.le_formula_copc_d, 3, 7, 1, 1)
        self.label_62 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_11.addWidget(self.label_62, 3, 9, 1, 1)
        self.label_63 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_11.addWidget(self.label_63, 0, 1, 1, 10)
        self.label_64 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_11.addWidget(self.label_64, 1, 1, 1, 10)
        self.groupBox_22 = QtGui.QGroupBox(self.groupBox_20)
        self.groupBox_22.setGeometry(QtCore.QRect(20, 160, 621, 121))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.gridLayoutWidget_15 = QtGui.QWidget(self.groupBox_22)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(20, 20, 581, 86))
        self.gridLayoutWidget_15.setObjectName(_fromUtf8("gridLayoutWidget_15"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.le_formula_coph_e = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_e.setObjectName(_fromUtf8("le_formula_coph_e"))
        self.gridLayout_16.addWidget(self.le_formula_coph_e, 3, 10, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem7, 3, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem8, 3, 5, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem9, 3, 8, 1, 1)
        self.le_formula_coph_a = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_a.setObjectName(_fromUtf8("le_formula_coph_a"))
        self.gridLayout_16.addWidget(self.le_formula_coph_a, 2, 10, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem10, 2, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem11, 2, 5, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem12, 2, 8, 1, 1)
        self.label_92 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_16.addWidget(self.label_92, 0, 0, 1, 1)
        self.label_97 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout_16.addWidget(self.label_97, 3, 0, 1, 1)
        self.le_formula_coph_b = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_b.setObjectName(_fromUtf8("le_formula_coph_b"))
        self.gridLayout_16.addWidget(self.le_formula_coph_b, 3, 1, 1, 1)
        self.le_formula_coph_f = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_f.setObjectName(_fromUtf8("le_formula_coph_f"))
        self.gridLayout_16.addWidget(self.le_formula_coph_f, 2, 1, 1, 1)
        self.le_formula_coph_m = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_m.setObjectName(_fromUtf8("le_formula_coph_m"))
        self.gridLayout_16.addWidget(self.le_formula_coph_m, 2, 4, 1, 1)
        self.label_98 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout_16.addWidget(self.label_98, 2, 0, 1, 1)
        self.label_99 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout_16.addWidget(self.label_99, 2, 6, 1, 1)
        self.label_105 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout_16.addWidget(self.label_105, 2, 9, 1, 1)
        self.le_formula_coph_n = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_n.setObjectName(_fromUtf8("le_formula_coph_n"))
        self.gridLayout_16.addWidget(self.le_formula_coph_n, 2, 7, 1, 1)
        self.label_106 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout_16.addWidget(self.label_106, 2, 3, 1, 1)
        self.label_107 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout_16.addWidget(self.label_107, 3, 3, 1, 1)
        self.le_formula_coph_c = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_c.setObjectName(_fromUtf8("le_formula_coph_c"))
        self.gridLayout_16.addWidget(self.le_formula_coph_c, 3, 4, 1, 1)
        self.label_108 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout_16.addWidget(self.label_108, 3, 6, 1, 1)
        self.le_formula_coph_d = QtGui.QLineEdit(self.gridLayoutWidget_15)
        self.le_formula_coph_d.setObjectName(_fromUtf8("le_formula_coph_d"))
        self.gridLayout_16.addWidget(self.le_formula_coph_d, 3, 7, 1, 1)
        self.label_109 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout_16.addWidget(self.label_109, 3, 9, 1, 1)
        self.label_110 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout_16.addWidget(self.label_110, 0, 1, 1, 10)
        self.label_111 = QtGui.QLabel(self.gridLayoutWidget_15)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout_16.addWidget(self.label_111, 1, 1, 1, 10)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 410, 661, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.btn_save_udf_param = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.btn_save_udf_param.setObjectName(_fromUtf8("btn_save_udf_param"))
        self.horizontalLayout_4.addWidget(self.btn_save_udf_param)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_set_intparam = QtGui.QWidget()
        self.tab_set_intparam.setObjectName(_fromUtf8("tab_set_intparam"))
        self.groupBox = QtGui.QGroupBox(self.tab_set_intparam)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 661, 241))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 621, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 581, 31))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.le_backfill_heat_coeff = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_backfill_heat_coeff.setObjectName(_fromUtf8("le_backfill_heat_coeff"))
        self.gridLayout.addWidget(self.le_backfill_heat_coeff, 0, 5, 1, 1)
        self.le_backfill_density = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_backfill_density.setObjectName(_fromUtf8("le_backfill_density"))
        self.gridLayout.addWidget(self.le_backfill_density, 0, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 0, 7, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 8, 1, 1)
        self.le_backfill_spec_heat = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_backfill_spec_heat.setObjectName(_fromUtf8("le_backfill_spec_heat"))
        self.gridLayout.addWidget(self.le_backfill_spec_heat, 0, 9, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 10, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 90, 621, 61))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 581, 31))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.le_pipe_heat_coeff = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.le_pipe_heat_coeff.setObjectName(_fromUtf8("le_pipe_heat_coeff"))
        self.gridLayout_2.addWidget(self.le_pipe_heat_coeff, 0, 5, 1, 1)
        self.le_pipe_density = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.le_pipe_density.setObjectName(_fromUtf8("le_pipe_density"))
        self.gridLayout_2.addWidget(self.le_pipe_density, 0, 1, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 0, 7, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 0, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 8, 1, 1)
        self.le_pipe_spec_heat = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.le_pipe_spec_heat.setObjectName(_fromUtf8("le_pipe_spec_heat"))
        self.gridLayout_2.addWidget(self.le_pipe_spec_heat, 0, 9, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 10, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 160, 621, 61))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 581, 31))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.le_soil_heat_coeff = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.le_soil_heat_coeff.setObjectName(_fromUtf8("le_soil_heat_coeff"))
        self.gridLayout_3.addWidget(self.le_soil_heat_coeff, 0, 5, 1, 1)
        self.le_soil_density = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.le_soil_density.setObjectName(_fromUtf8("le_soil_density"))
        self.gridLayout_3.addWidget(self.le_soil_density, 0, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 0, 7, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 6, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 8, 1, 1)
        self.le_soil_spec_heat = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.le_soil_spec_heat.setObjectName(_fromUtf8("le_soil_spec_heat"))
        self.gridLayout_3.addWidget(self.le_soil_spec_heat, 0, 9, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 0, 10, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_set_intparam)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 270, 661, 191))
        self.groupBox_5.setBaseSize(QtCore.QSize(50, 0))
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 621, 61))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 581, 31))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.le_init_ground_temp = QtGui.QLineEdit(self.gridLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_init_ground_temp.sizePolicy().hasHeightForWidth())
        self.le_init_ground_temp.setSizePolicy(sizePolicy)
        self.le_init_ground_temp.setBaseSize(QtCore.QSize(0, 0))
        self.le_init_ground_temp.setObjectName(_fromUtf8("le_init_ground_temp"))
        self.gridLayout_4.addWidget(self.le_init_ground_temp, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 0, 2, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem20, 0, 3, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 90, 621, 81))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_11)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 581, 48))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.le_loop_velocity = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.le_loop_velocity.setObjectName(_fromUtf8("le_loop_velocity"))
        self.gridLayout_5.addWidget(self.le_loop_velocity, 0, 1, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 0, 3, 1, 1)
        self.label_51 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_5.addWidget(self.label_51, 0, 0, 1, 1)
        self.label_52 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_5.addWidget(self.label_52, 0, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.le_loop_intensity = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.le_loop_intensity.setObjectName(_fromUtf8("le_loop_intensity"))
        self.gridLayout_5.addWidget(self.le_loop_intensity, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 1, 2, 1, 1)
        self.label_50 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_5.addWidget(self.label_50, 1, 4, 1, 1)
        self.le_loop_hydr_diameter = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.le_loop_hydr_diameter.setObjectName(_fromUtf8("le_loop_hydr_diameter"))
        self.gridLayout_5.addWidget(self.le_loop_hydr_diameter, 1, 5, 1, 1)
        self.label_49 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_5.addWidget(self.label_49, 1, 6, 1, 1)
        self.tabWidget.addTab(self.tab_set_intparam, _fromUtf8(""))
        self.tab_simulation = QtGui.QWidget()
        self.tab_simulation.setObjectName(_fromUtf8("tab_simulation"))
        self.groupBox_18 = QtGui.QGroupBox(self.tab_simulation)
        self.groupBox_18.setGeometry(QtCore.QRect(20, 20, 661, 111))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.gridLayoutWidget_12 = QtGui.QWidget(self.groupBox_18)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(20, 30, 621, 61))
        self.gridLayoutWidget_12.setObjectName(_fromUtf8("gridLayoutWidget_12"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.le_fluent_time_year = QtGui.QLineEdit(self.gridLayoutWidget_12)
        self.le_fluent_time_year.setObjectName(_fromUtf8("le_fluent_time_year"))
        self.gridLayout_13.addWidget(self.le_fluent_time_year, 1, 1, 1, 1)
        self.label_90 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_13.addWidget(self.label_90, 0, 0, 1, 1)
        self.le_fluent_time_hour = QtGui.QLineEdit(self.gridLayoutWidget_12)
        self.le_fluent_time_hour.setObjectName(_fromUtf8("le_fluent_time_hour"))
        self.gridLayout_13.addWidget(self.le_fluent_time_hour, 1, 7, 1, 1)
        self.label_89 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_13.addWidget(self.label_89, 1, 0, 1, 1)
        self.label_94 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout_13.addWidget(self.label_94, 1, 2, 1, 1)
        self.le_fluent_time_step = QtGui.QLineEdit(self.gridLayoutWidget_12)
        self.le_fluent_time_step.setObjectName(_fromUtf8("le_fluent_time_step"))
        self.gridLayout_13.addWidget(self.le_fluent_time_step, 0, 1, 1, 1)
        self.label_95 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_13.addWidget(self.label_95, 1, 4, 1, 1)
        self.label_93 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_13.addWidget(self.label_93, 0, 2, 1, 1)
        self.label_96 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_13.addWidget(self.label_96, 1, 6, 1, 1)
        self.le_fluent_time_day = QtGui.QLineEdit(self.gridLayoutWidget_12)
        self.le_fluent_time_day.setObjectName(_fromUtf8("le_fluent_time_day"))
        self.gridLayout_13.addWidget(self.le_fluent_time_day, 1, 5, 1, 1)
        self.le_fluent_time_month = QtGui.QLineEdit(self.gridLayoutWidget_12)
        self.le_fluent_time_month.setObjectName(_fromUtf8("le_fluent_time_month"))
        self.gridLayout_13.addWidget(self.le_fluent_time_month, 1, 3, 1, 1)
        self.label_88 = QtGui.QLabel(self.gridLayoutWidget_12)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_13.addWidget(self.label_88, 1, 8, 1, 1)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_simulation)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(90, 210, 541, 80))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem22, 1, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem23, 1, 1, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem24, 1, 2, 1, 1)
        self.btn_run_sim = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.btn_run_sim.setObjectName(_fromUtf8("btn_run_sim"))
        self.gridLayout_7.addWidget(self.btn_run_sim, 2, 1, 1, 1)
        self.btn_save_jou_param = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.btn_save_jou_param.setObjectName(_fromUtf8("btn_save_jou_param"))
        self.gridLayout_7.addWidget(self.btn_save_jou_param, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_simulation, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_A = QtGui.QMenu(self.menubar)
        self.menu_A.setObjectName(_fromUtf8("menu_A"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_menu_quit = QtGui.QAction(MainWindow)
        self.action_menu_quit.setObjectName(_fromUtf8("action_menu_quit"))
        self.action_menu_about = QtGui.QAction(MainWindow)
        self.action_menu_about.setObjectName(_fromUtf8("action_menu_about"))
        self.action_Fluent = QtGui.QAction(MainWindow)
        self.action_Fluent.setObjectName(_fromUtf8("action_Fluent"))
        self.menu.addSeparator()
        self.menu.addAction(self.action_menu_quit)
        self.menu_A.addAction(self.action_menu_about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_A.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Fluent仿真文件", None))
        self.btn_open_fluent_cas.setText(_translate("MainWindow", "打开", None))
        self.btn_open_fluent_jou.setText(_translate("MainWindow", "打开", None))
        self.label_100.setText(_translate("MainWindow", "命令流文件(*.jou)", None))
        self.label_101.setText(_translate("MainWindow", "模型文件(*.cas)", None))
        self.btn_load_jou_param.setText(_translate("MainWindow", "载入参数", None))
        self.btn_open_fluent_udf.setText(_translate("MainWindow", "打开", None))
        self.label_102.setText(_translate("MainWindow", "UDF文件(*.c)", None))
        self.label_103.setText(_translate("MainWindow", "建筑负荷文件", None))
        self.btn_open_fluent_load.setText(_translate("MainWindow", "打开", None))
        self.btn_load_udf_param.setText(_translate("MainWindow", "载入参数", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "工程文件", None))
        self.btn_open_proj.setText(_translate("MainWindow", "打开", None))
        self.label_91.setText(_translate("MainWindow", "工程文件(*.proj)  ", None))
        self.btn_new_proj.setText(_translate("MainWindow", "新建", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "Fluent路径", None))
        self.btn_open_fluent_path.setText(_translate("MainWindow", "打开", None))
        self.label_104.setText(_translate("MainWindow", "Fluent安装路径     ", None))
        self.btn_save_proj.setText(_translate("MainWindow", "保存工程设置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "文件设置", None))
        self.groupBox_20.setTitle(_translate("MainWindow", "热泵机组参数修改", None))
        self.groupBox_21.setTitle(_translate("MainWindow", "制冷工程", None))
        self.label_59.setText(_translate("MainWindow", "公式:", None))
        self.label_25.setText(_translate("MainWindow", "b=", None))
        self.label_71.setText(_translate("MainWindow", "f=", None))
        self.label_68.setText(_translate("MainWindow", "n=", None))
        self.label_73.setText(_translate("MainWindow", "a=", None))
        self.label_74.setText(_translate("MainWindow", "m=", None))
        self.label_26.setText(_translate("MainWindow", "c=", None))
        self.label_60.setText(_translate("MainWindow", "d=", None))
        self.label_62.setText(_translate("MainWindow", "e=", None))
        self.label_63.setText(_translate("MainWindow", "COPC = f * e ^ (m/(q+n)) *  (a * t^4 + b * t^3 + c * t^2 + d * t + e)", None))
        self.label_64.setText(_translate("MainWindow", "(注: q为负荷率， f、m、n、a、b、c、d、e为样本拟合系数)", None))
        self.groupBox_22.setTitle(_translate("MainWindow", "制热工程", None))
        self.label_92.setText(_translate("MainWindow", "公式:", None))
        self.label_97.setText(_translate("MainWindow", "b=", None))
        self.label_98.setText(_translate("MainWindow", "f=", None))
        self.label_99.setText(_translate("MainWindow", "n=", None))
        self.label_105.setText(_translate("MainWindow", "a=", None))
        self.label_106.setText(_translate("MainWindow", "m=", None))
        self.label_107.setText(_translate("MainWindow", "c=", None))
        self.label_108.setText(_translate("MainWindow", "d=", None))
        self.label_109.setText(_translate("MainWindow", "e=", None))
        self.label_110.setText(_translate("MainWindow", "COPH = f * e ^ (m/(q+n)) *  (a * t^4 + b * t^3 + c * t^2 + d * t + e)", None))
        self.label_111.setText(_translate("MainWindow", "(注: q为负荷率， f、m、n、a、b、c、d、e为样本拟合系数)", None))
        self.btn_save_udf_param.setText(_translate("MainWindow", "保存UDF参数", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "外部参数设置", None))
        self.groupBox.setTitle(_translate("MainWindow", "物性参数", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "回填材料", None))
        self.label_3.setText(_translate("MainWindow", "(W/m.K)", None))
        self.label_2.setText(_translate("MainWindow", "导热系数", None))
        self.label.setText(_translate("MainWindow", "密度", None))
        self.label_4.setText(_translate("MainWindow", "(kg/m3)", None))
        self.label_5.setText(_translate("MainWindow", "比热", None))
        self.label_6.setText(_translate("MainWindow", "(J/kg.K)", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "管道", None))
        self.label_7.setText(_translate("MainWindow", "(W/m.K)", None))
        self.label_8.setText(_translate("MainWindow", "导热系数", None))
        self.label_9.setText(_translate("MainWindow", "密度", None))
        self.label_10.setText(_translate("MainWindow", "(kg/m3)", None))
        self.label_11.setText(_translate("MainWindow", "比热", None))
        self.label_12.setText(_translate("MainWindow", "(J/kg.K)", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "土壤", None))
        self.label_13.setText(_translate("MainWindow", "(W/m.K)", None))
        self.label_14.setText(_translate("MainWindow", "导热系数", None))
        self.label_15.setText(_translate("MainWindow", "密度", None))
        self.label_16.setText(_translate("MainWindow", "(kg/m3)", None))
        self.label_17.setText(_translate("MainWindow", "比热", None))
        self.label_18.setText(_translate("MainWindow", "(J/kg.K)", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "单值性条件", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "初始地温", None))
        self.label_21.setText(_translate("MainWindow", "初始地温           ", None))
        self.label_22.setText(_translate("MainWindow", "(K)", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "入口边界条件", None))
        self.label_51.setText(_translate("MainWindow", "循环体流速", None))
        self.label_52.setText(_translate("MainWindow", "(m/s)", None))
        self.label_19.setText(_translate("MainWindow", "循环体紊流强度", None))
        self.label_20.setText(_translate("MainWindow", "(%)", None))
        self.label_50.setText(_translate("MainWindow", "循环体水力直径", None))
        self.label_49.setText(_translate("MainWindow", "(m)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_set_intparam), _translate("MainWindow", "换热器参数设置", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "迭代设置", None))
        self.label_90.setText(_translate("MainWindow", "时间步长", None))
        self.label_89.setText(_translate("MainWindow", "运行时间", None))
        self.label_94.setText(_translate("MainWindow", "年", None))
        self.label_95.setText(_translate("MainWindow", "月", None))
        self.label_93.setText(_translate("MainWindow", "(秒)", None))
        self.label_96.setText(_translate("MainWindow", "天", None))
        self.label_88.setText(_translate("MainWindow", "小时", None))
        self.btn_run_sim.setText(_translate("MainWindow", "调用Fluent运行仿真", None))
        self.btn_save_jou_param.setText(_translate("MainWindow", "保存仿真参数", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_simulation), _translate("MainWindow", "系统耦合模拟", None))
        self.menu.setTitle(_translate("MainWindow", "文件(&F)", None))
        self.menu_A.setTitle(_translate("MainWindow", "帮助(&H)", None))
        self.action_menu_quit.setText(_translate("MainWindow", "退出(Ctrl+&Q)", None))
        self.action_menu_about.setText(_translate("MainWindow", "关于(&A)", None))
        self.action_Fluent.setText(_translate("MainWindow", "打开Fluent日志文件", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

